/* CREATION DES TABLES */

BEGIN;

DROP TABLE IF EXISTS "subject", "verb", "complement", "archive";

CREATE TABLE IF NOT EXISTS"subject" (
    "id" serial PRIMARY Key,
    "name" text NOT NULL
);

CREATE TABLE IF NOT EXISTS"verb" (
    "id" serial PRIMARY Key,
    "name" text NOT NULL
);

CREATE TABLE IF NOT EXISTS"complement" (
    "id" serial PRIMARY Key,
    "name" text NOT NULL
);

CREATE TABLE IF NOT EXISTS"archive" (
    "id" serial PRIMARY Key,
    "phrase" text
);

COMMIT;

/* INJECTIONS DES DONNEES DANS LES TABLES */

BEGIN;

INSERT INTO "subject" ("id","name") VALUES
(1, 'Mon chat'),
(2, 'Mon chien'),
(3, 'Mon hamster'),
(4, 'Mon poney'),
(5, 'Ma licorne'),
(6, 'Ma pantoufle'),
(7, 'Mon stylo'),
(8, 'Mon écharpe'),
(9, 'Ma couette'),
(10, 'Ma voiture'),
(11, 'Mon vélo'),
(12, 'Ma voisine'),
(13, 'Mon papy'),
(14, 'Ma mamie'),
(15, 'Mon frère'),
(16, 'Ma soeur'),
(17, 'Ma prof'),
(18, 'Mon prof'),
(19, 'Ma souris'),
(20, 'Ma pelle'),
(21, 'Ma peluche'),
(22, 'Mon mug'),
(23, 'Ma pop'),
(24, 'Un canari'),
(25, 'Un blaireau'),
(26, 'Un putois'),
(27, 'Une cigogne'),
(28, 'Une aigle'),
(29, 'Un chameau'),
(30, 'Un poteau'),
(31, 'Une porte'),
(32, 'Une fenêtre'),
(33, 'Ma trousse'),
(34, 'Mon sac'),
(35, 'Mon devoir'),
(36, 'Mon smartphone'),
(37, 'Ma Wii'),
(38, 'Ma PS4'),
(39, 'Ma PS5'),
(40, 'Ma Xbox'),
(41, 'Mon pc'),
(42, 'Ma Switch'),
(43, 'Pikachu'),
(44, 'Salamèche'),
(45, 'Bulbizar'),
(46, 'Harry'),
(47, 'Hermione'),
(48, 'Ronald'),
(49, 'Fred'),
(50, 'Georges'),
(51, 'Sirius'),
(52, 'Remus'),
(53, 'James'),
(54, 'Lily'),
(55, 'Severus'),
(56, 'Lucius'),
(57, 'Draco'),
(58, 'Voldemort'),
(59, 'Bellatrix'),
(60, 'Dobby'),
(61, 'Sauron'),
(62, 'Frodon'),
(63, 'Sam'),
(64, 'Merry'),
(65, 'Pippin'),
(66, 'Gandalf'),
(67, 'Gimli'),
(68, 'Legolas'),
(69, 'Aragorn'),
(70, 'Saroumane'),
(71, 'Aragog'),
(72, 'Touffu'),
(73, 'Crockdur'),
(74, 'Un dragon'),
(75, 'Une licorne'),
(76, 'Un niffleur'),
(77, 'Rondoudou'),
(78, 'Dracofeu'),
(79, 'Tortank'),
(80, 'Magicarpe'),
(81, 'Leviathor'),
(82, 'Un pokemon'),
(83, 'Un veaudelune'),
(84, 'Norbert'),
(85, 'Grindelwald'),
(86, 'Dumbledore'),
(87, 'Un shaman'),
(88, 'Un zombie'),
(89, 'Un troll'),
(90, 'Un gobelin'),
(91, 'Un dev back'),
(92, 'Un dev front'),
(93, 'Un tuyau'),
(94, 'Un oeuf'),
(95, 'Une poule'),
(96, 'Un basilic'),
(97, 'Une wyverne'),
(98, 'Un bouc'),
(99, 'Une pomme'),
(100, 'Un lutin'),
(101, 'Un martien'),
(102, 'Une météorite'),
(103, 'Un tsunami'),
(104, 'Une tornade'),
(105, 'Un ouragan'),
(106, 'Un botruc'),
(107, 'Un hyppogriffe'),
(108, 'Une chimère'),
(109, 'Une sorcière'),
(110, 'Un mage'),
(111, 'Une fée');

INSERT INTO "verb" ("id","name") VALUES
(1, 'a mangé'),
(2, 'a brûlé'),
(3, 'a bavé sur'),
(4, 'a écrit sur'),
(5, 'a déchiquetté'),
(6, 'a cassé'),
(7, 'a massacré'),
(8, 'a béni'),
(9, 'a maudit'),
(10, 'a immolé'),
(11, 'a noyé'),
(12, 'a vomi sur'),
(13, 'a chié sur'),
(14, 'a pissé sur'),
(15, 'a grogné'),
(16, 'a crié sur'),
(17, 'a gerbé'),
(18, 'a acheté'),
(19, 'a assemblé'),
(20, 'a organisé'),
(21, 'a codé'),
(22, 'a séduit'),
(23, 'a traduit'),
(24, 'a opéré'),
(25, 'a fabriqué'),
(26, 'a copié'),
(27, 'a bu'),
(28, 'a sniffé'),
(29, 'a fumé'),
(30, 'a argumenté avec'),
(31, 'a audité'),
(32, 'a calculé'),
(33, 'a conçu'),
(34, 'a construit'),
(35, 'a convaincu'),
(36, 'a défendu'),
(37, 'a developpé'),
(38, 'a élaboré'),
(39, 'a négocié avec'),
(40, 'a séduit'),
(41, 'a valorisé'),
(42, 'a examiné'),
(43, 'a piloté'),
(44, 'a chantonné avec'),
(45, 'a chanté sur'),
(46, 'a éclaboussé'),
(47, 'a sautillé avec'),
(48, 'a sauté sur'),
(49, 'a interrogé'),
(50, 'a interviewé'),
(51, 'a craché avec'),
(52, 'a craché sur'),
(53, 'a mugi'),
(54, 'a griffé'),
(55, 'a dansé sur'),
(56, 'a sauté avec'),
(57, 'a dansé avec'),
(58, 'a chanté avec'),
(59, 'a sauté avec'),
(60, 'a rendu sur'),
(61, 'a salivé sur'),
(62, 'a frôlé'),
(63, 'a volé avec'),
(64, 'a bondi sur'),
(65, 'a bondi avec'),
(66, 'a sautillé sur'),
(67, 'a feulé sur'),
(68, 'a grogné sur'),
(69, 'a miaulé sur'),
(70, 'a rugi sur'),
(71, 'a hurlé avec'),
(72, 'a pété sur'),
(73, 'a tapé'),
(74, 'a photographié'),
(75, 'a filmé'),
(76, 'a boxé avec'),
(77, 'a couché avec'),
(78, 'a dormi avec'),
(79, 'a dormi sur'),
(80, 'a dormi sous'),
(81, 'a escamoté'),
(82, 'a râlé contre'),
(83, 'a râlé sur'),
(84, 'a râlé avec'),
(85, 'a déferlé sur'),
(86, 'a déferlé avec'),
(87, 'a parlé avec'),
(88, 'a kidnappé'),
(89, 'a enlevé'),
(90, 'a subtilisé'),
(91, 'a fait disparaître'),
(92, 'a arraché'),
(93, 'a détrôné'),
(94, 'a intronisé'),
(95, 'a esquivé'),
(96, 'a lassé'),
(97, 'a enrubanné'),
(98, 'a ligoté'),
(99, 'a saucissoné'),
(100, 'a attaché'),
(101, 'a détaché'),
(102, 'a libéré'),
(103, 'a lévité avec'),
(104, 'a aimé'),
(105, 'a détesté'),
(106, 'a hué'),
(107, 'a conspué'),
(108, 'a influencé'),
(109, 'a gémi avec'),
(110, 'a pleuré avec'),
(111, 'a rigolé avec');

INSERT INTO "complement" ("id","name") VALUES
(1, 'mes devoirs de philosophie'),
(2, 'mes pantoufles de vair'),
(3, 'mon lit avec la couette Ladybug'),
(4, 'mon ukulele en papier mâché'),
(5, 'un ukulele en paille de bambou'),
(6, 'ma flûte en bois de pipo'),
(7, 'une flûte enchantée'),
(8, 'ma guitare dédicacée par Maïté'),
(9, 'une guitare électrique Trempette'),
(10, 'mon trombone à coulisse'),
(11, 'un trombone belle-mère'),
(12, 'une pantoufle en peau de zob'),
(13, 'une tongue Adadas'),
(14, 'une sandale Matien'),
(15, 'mes baskets à Led'),
(16, 'les bottes du chat Potté'),
(17, 'un oreiller en plumes de zoi'),
(18, 'une couette à bretelles argentées'),
(19, 'mon plaid préféré Harry Potter'),
(20, 'ma réplique de Pikachu'),
(21, 'ma pop Deadpool'),
(22, 'mon poster Ready Player One'),
(23, 'mes Doc Martens'),
(24, 'mon pantalon troué à franges'),
(25, 'ma corne de licorne à paillettes'),
(26, 'mon kilt en tartan à pois'),
(27, 'un bachi bouzouk'),
(28, 'un moule à gauffres'),
(29, 'le Capitaine Haddock'),
(30, 'Celui-Dont-On-Ne-Doit-Pas-Dire-Le-Nom'),
(31, 'Albus Perceval Wulfric Dumbledore'),
(32, 'un Mangemort sous LSD'),
(33, 'Tintin et Milou en robes fleuries'),
(34, 'la reine en string sur un monocycle'),
(35, 'Stéphanie de Monaco'),
(36, 'la casa del Rey'),
(37, 'un mug à deux anses'),
(38, 'un bol breton en céramique'),
(39, 'un brancardier sénile'),
(40, 'une cueilleuse de myrtilles'),
(41, 'un kamikaze en tenue helvète'),
(42, 'le comte Dracula'),
(43, 'un ver de terre récidiviste'),
(44, 'un saucisson domestiqué'),
(45, 'un pignouf en short'),
(46, 'des jongleuses de truelle'),
(47, 'les mignons de Gru'),
(48, 'Papuche la licorne'),
(49, 'un oliphant rose'),
(50, 'un tigre sous extasy'),
(51, 'un lion sous cannabis'),
(52, 'un singe en jupe de cuir'),
(53, 'le boucher Sanzos'),
(54, 'la couturière Kipik'),
(55, 'les étudiants en tongues'),
(56, 'les étudiantes en toge'),
(57, 'la mère Michel'),
(58, 'le père Lustucru'),
(59, 'une souris verte'),
(60, 'un escargot bicéphale borgne'),
(61, 'un mouton à 5 pattes'),
(62, 'un troupeau de chupacabra'),
(63, 'un loup-garou végétarien'),
(64, 'un lapin-garou tout pelé'),
(65, 'un chat-garou siamois'),
(66, 'un thérianthrophe steampunk'),
(67, 'une vieille cagole'),
(68, 'Petit-Pied, le petit dinosaure'),
(69, 'un pharaon mal momifié'),
(70, 'la princesse au petit-pois'),
(71, 'un chevalier télékinésiste'),
(72, 'un mec chauve qui parle dans la tête'),
(73, 'un type poilu avec des ongles en métal'),
(74, 'un gobelin vert qui parle bizarre'),
(75, 'un gamin roux qui vit dans un terrier'),
(76, 'un dev qui vit dans sa cave'),
(77, 'un vieux barbu en robe mauve'),
(78, 'un vilan méchant sans nez'),
(79, 'un serpent à 2 têtes'),
(80, 'un chien à 3 têtes'),
(81, 'un oiseau qui crame tout seul parfois'),
(82, 'le Professeur Roge et sa page 394'),
(83, 'un Détraqueur qui aime les peluches'),
(84, 'un troll qui tricote'),
(85, 'la Fée Pachié'),
(86, 'la Fée Lonie'),
(87, 'un chat troglodyte'),
(88, 'un cheval à bascule'),
(89, 'un chinchilla albinos'),
(90, 'un aligator zébré'),
(91, 'un serpent à plumes'),
(92, 'un cochon qui glougloute'),
(93, 'une ballerine unijambiste'),
(94, 'un gros plombier en salopette rouge'),
(95, 'un grand plombier en salopette verte'),
(96, 'un elfe qui asmate des poules'),
(97, 'un semi-homme très brave'),
(98, 'un nain en bas-résille'),
(99, 'un blaireau travailleur'),
(100, 'un serpent malicieux'),
(101, 'un lion courageux'),
(102, 'un corbeau savant'),
(103, 'un machin-chose-bidule-truc'),
(104, 'le schimlblick'),
(105, 'une mini-pop de Noël'),
(106, 'un cerbère agoraphobe'),
(107, 'la voisine en peignoir et crocks rose'),
(108, 'une licorne constipée'),
(109, 'un dragon au look émo'),
(110, 'le Diable en personne'),
(111, 'une potterhead pas très subtile');

INSERT INTO "archive" ("id","phrase") VALUES
(1, 'mon chaton a vomi sur mon agenda');

COMMIT;

/* PETITE REGLE POUR RECUPERER LE DERNIER ID A LA CREATION D'UNE NOUVELLE ENTREE VIA UNE INTERFACE */
/* PAS SURE DE L'UTILISER ICI MAIS ON SAIT JAMAIS */

BEGIN;

-- PostGres avec le type serial n'incrémente pas automatiquement de façon implicite la séquence rattaché à la colonne !
-- Il faut donc mettre à jour la valeur courante de chacune des séquences en séléctionnant l'id maximum de chaque table

SELECT setval('subject_id_seq', (SELECT MAX(id) from "subject"));
SELECT setval('verb_id_seq', (SELECT MAX(id) from "verb"));
SELECT setval('complement_id_seq', (SELECT MAX(id) from "complement"));
SELECT setval('archive_id_seq', (SELECT MAX(id) from "archive"));

COMMIT;